In [1]:
import time
import time, psutil, os
start = time.time()
m0 = psutil.Process(os.getpid()).memory_info().rss / 1024**2

In [2]:
import pandas as pd

ficheiro = r"C:\Users\1420844\Downloads\addressGeoLoc_export_20221006.csv"

df = pd.read_csv(ficheiro, sep=",", quotechar='"', skiprows=1,
                  names=["MORADA", "CP", "LOCALIDADE", "LATITUDE", "LONGITUDE"])

In [3]:
df.head()

,MORADA,CP,LOCALIDADE,LATITUDE,LONGITUDE
0,RUA CESARIO VERDE LOTE 3 A DAS LEBR,2660,FRIELAS,38.852697456,-9.16971532999997
1,RUA DO ROXICO NR50,3865-110,FERMELA,40.709808191,-8.54878568099997
2,AVENIDA 13 DE MAIO N 536,3885-227,CORTEGACA OVR,40.94109138,-8.61864986999996
3,AV REINALDO SANTOS N 24 3 DTO,2675-673,ODIVELAS,38.7926955990001,-9.18881750599996
4,RUA DO BARREIRO N 547,4405-730,VILA NOVA DE GAIA,41.113905909,-8.63062512299996

In [4]:
df.describe()

                 MORADA       CP LOCALIDADE      LATITUDE          LONGITUDE
count           2168408  2168409    2168183       2168409            2168409
unique          2009685    94186       1777        691906             682766
top     R DA GUARDA 718     4450     LISBOA  41.221724958  -8.70396501899995
freq                 68     8798     305258           326                326

In [5]:
# garantir que a coluna CP é string
df["CP"] = df["CP"].astype(str)

# filtrar e contar
contagem = df[df["CP"].str[:4].isin(["4830", "4850"])]["MORADA"].count()

print("Número de moradas:", contagem)

Número de moradas: 1158

In [6]:
df_filtrado = df[df["CP"].str[:4].isin(["4830", "4850"])]
df_filtrado

,MORADA,CP,LOCALIDADE,LATITUDE,LONGITUDE
1492,RUA COMANDANTE LUIS PINTO DA SILVA NR 37,4830,POVOA DE LANHOSO,41.573881,-8.268431
2862,AVENIDA DA CAPELA 147,4830,POVOA DE LANHOSO,41.602910728,-8.31333931399996
5469,RUA NEUVES MAISONS NUMERO 211 1 DIREITO,4830-550,POVOA DE LANHOSO,41.573046436,-8.26624732199997
7366,RUA DE SAINHAS NR 12 HOTEL NASCENTE DO AVE,4850,VIEIRA DO MINHO,41.572839984,-8.12032993799994
7590,AV DAS PENAS N 158 SOBRADELO DA GOMA,4830,POVOA DE LANHOSO,41.5648747560001,-8.18242852399993
...,...,...,...,...,...
2162431,RUA CREMILDO PEREIRA 404 QUINTA D ALEM,4830,POVOA DE LANHOSO,41.599177162,-8.28832357999994
2162814,RUA DR ALBINO JOSE DA SILVA 21 1,4830,POVOA DE LANHOSO,41.57227,-8.27026
2165032,TRAVESSA DA CACHADA N 136 POVOA DE LANHOSO,4830,POVOA DE LANHOSO,41.5464912840001,-8.28301312999997
2165657,RUA DA QUINTA N 179 B,4830-379,LOUREDO PVL,41.5465713200001,-8.28988375599994
2167840,RUA 5 DE SETEMBRO N94 N94 RC ESQUERDO,4830,PA VOA DE LANHOSO,41.57924,-8.273131

In [8]:
# ==========================
# 1. Filtrar colunas e CP
# ==========================
df_filtrado = df.loc[
    df["CP"].str[:4].isin(["4830", "4850"]),
    ["MORADA", "CP", "LOCALIDADE"]
]

df_filtrado

,MORADA,CP,LOCALIDADE
1492,RUA COMANDANTE LUIS PINTO DA SILVA NR 37,4830,POVOA DE LANHOSO
2862,AVENIDA DA CAPELA 147,4830,POVOA DE LANHOSO
5469,RUA NEUVES MAISONS NUMERO 211 1 DIREITO,4830-550,POVOA DE LANHOSO
7366,RUA DE SAINHAS NR 12 HOTEL NASCENTE DO AVE,4850,VIEIRA DO MINHO
7590,AV DAS PENAS N 158 SOBRADELO DA GOMA,4830,POVOA DE LANHOSO
...,...,...,...
2162431,RUA CREMILDO PEREIRA 404 QUINTA D ALEM,4830,POVOA DE LANHOSO
2162814,RUA DR ALBINO JOSE DA SILVA 21 1,4830,POVOA DE LANHOSO
2165032,TRAVESSA DA CACHADA N 136 POVOA DE LANHOSO,4830,POVOA DE LANHOSO
2165657,RUA DA QUINTA N 179 B,4830-379,LOUREDO PVL
2167840,RUA 5 DE SETEMBRO N94 N94 RC ESQUERDO,4830,PA VOA DE LANHOSO

In [12]:
# ==========================
# 2. Exportar para Excel com colunas definidas
# ==========================
# Lista de colunas finais
colunas_final = ["MORADA", "CP", "LOCALIDADE"]

# Criar DataFrame final (colunas extra ficam a NaN)
df_final = df_filtrado.reindex(columns=colunas_final)

# Caminho da pasta Downloads do utilizador
downloads = os.path.join(os.path.expanduser("~"), "Downloads")

# Nome do ficheiro
ARQ_OUT = os.path.join(downloads, "Moradas_4830_4850.xlsx")

# Exportar
df_final.to_excel(ARQ_OUT, index=False)

In [7]:
m1 = psutil.Process(os.getpid()).memory_info().rss / 1024**2
print("Tempo Pandas:", round(time.time() - start, 2), "segundos")
print("Memória Pandas:", round(m1 - m0, 2), "MB")

Tempo Pandas: 30.39 segundos
Memória Pandas: 585.31 MB